def testing():
    try:
        in_try = 1
    except IOError or AssertionError:
        in_except = 2

